# Generated by Django 3.1.7 on 2021-04-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
    ]
